import OnlineWorkBroll from './broll/OnlineWorkBroll';
import EditingTimelineBroll from './broll/EditingTimelineBroll';
import SocialMediaScrollBroll from './broll/SocialMediaScrollBroll';
import GlobalClientsBroll from './broll/GlobalClientsBroll';
import PracticalEditingBroll from './broll/PracticalEditingBroll';
import TelegramScreenRecordBroll from './broll/TelegramScreenRecordBroll';
import PdfCoverAnimationBroll from './broll/PdfCoverAnimationBroll';
import TypingCommentBroll from './broll/TypingCommentBroll';

export const videoData = {
  title: "Rofi",
  showVideo: true,
  mainVideo: require("./Rofi1.mp4"),
  brolls: [
    { component: OnlineWorkBroll, startFrame: 150, endFrame: 262 },
    { component: EditingTimelineBroll, startFrame: 300, endFrame: 350 },
    { component: SocialMediaScrollBroll, startFrame: 525, endFrame: 646 },
    { component: GlobalClientsBroll, startFrame: 1030, endFrame: 1130 },
    { component: PracticalEditingBroll, startFrame: 1250, endFrame: 1390 },
    { component: TelegramScreenRecordBroll, startFrame: 1590, endFrame: 1765 },
    { component: PdfCoverAnimationBroll, startFrame: 1790, endFrame: 1846 },
    { component: TypingCommentBroll, startFrame: 1890, endFrame: 1980 },
    {
      startFrame: 5,
      endFrame: 40,
      uiType: "moneyHook",
      offsetY: 400,
      offsetX: 0, 
      uiProps: {
        scale: 1.5,
        color: "#3d77fe", 
        durationInFrames: 40 - 5, 
      },
    },
    {
      startFrame: 55,
      endFrame: 112,
      uiType: "circleTimer",
      offsetY: 400,
      offsetX: 0,
      uiProps: {
        seconds: 30,      
        countDirection: "down",
        size: 400,
        strokeWidth: 40,
        color: "#3d77fe",
        durationInFrames: 112 - 55,
      },
    },
    {
      startFrame: 450,
      endFrame: 495,
      uiType: "numberPop",
      offsetY: 400,
      offsetX: 0,
      uiProps: {
        items: ["10", "20", "50"],
        suffix: "?",
        color: "#3d77fe",
        staggerFrames: 8,
        durationInFrames: 495 - 450},
    },
    {
      startFrame: 660,
      endFrame: 745,
      uiType: "growthTrend",
      offsetY: 400,
      uiProps: { text: "High Demand", size:2, color: "#3d77fe", durationInFrames: 745 - 660 },
    },
    {
      startFrame: 797,
      endFrame: 850,
      uiType: "iconReveal",
      offsetY: 400,
      uiProps: {
        text: "Rofi Edits",
        imageSrc: "Rofi.png",
        color: "#3d77fe",
        size: 1.7,
        durationInFrames: 850 - 797,
      },
    },    
    {
      startFrame: 1200,
      endFrame: 1250,
      uiType: "checkBadge",
      offsetY: -300,
      offsetX: -320,
      uiProps: { text: "Practical", color: "#22D3EE", durationInFrames: 1250 - 1200 },
    }, 
    {
      startFrame: 1475,
      endFrame: 1525,
      uiType: "onlineBadge",
      offsetY: 400,
      uiProps: { text: "100% Online", size:1.5, color: "#3B82F6", durationInFrames: 1525 - 1475 },
    },
    {
      startFrame: 1846,
      endFrame: 1890,
      uiType: "freeBadge",
      offsetY: 400,
      uiProps: { text: "FREE", size:1.5, color: "#F43F5E", durationInFrames: 1890 - 1846 },
    }    
  ],
  subtitles: [
    { text: "በወር ተጨማሪ", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    animation: "SmoothRevealText",
    fontSize: 72, 
    startFrame: 112, 
    endFrame: 150 }, 
    
    { text: "ገንዘቦችን ለመስራት", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80, 
    startFrame: 120, 
    endFrame: 150 },
    
    { text: "ከእነዚህ ስራዎች", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,     
    startFrame: 262,
    endFrame: 300 },
    
    { text: "መካከል ደግሞ", 
    bottomOffset: 400,
    fontFamilyName: "SurGraphics",
    animation: "SmoothRevealText",
    fontSize: 72,     
    startFrame: 272,
    endFrame: 300 },  
    
    { text: "ቆይ እዚህ ጋር", 
    bottomOffset: 476,
    fontFamilyName: "SurGraphics",
    animation: "SmoothRevealText",
    fontSize: 72,     
    startFrame: 350,
    endFrame: 400 },
    
    { text: "አንድ ጥያቄ ልጠይቃችሁ", 
    bottomOffset: 400,
    fontFamilyName: "SurGraphics",
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"],
    fontSize: 80,     
    startFrame: 360,
    endFrame: 400 },    
    
    { text: "ዛሬ ምን ያህል", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 400, 
    endFrame: 450 },
    
    { text: "videos ተመልክታችኋል",
    bottomOffset: 400,
    fontFamilyName: "SurGraphics",
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"],
    fontSize: 80,     
    startFrame: 410,
    endFrame: 450 },
    
    { text: "እናንተም ከእነሱ መካከል", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 745,
    endFrame: 797},
    
   { text: "እንድትሆኑ በማሰብ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 755,
    endFrame: 797},
    
    { text: "Video Editing program",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 70,    
    startFrame: 850, 
    endFrame: 904 },
    
   { text: "አዘጋጅተንላችኋል።",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 860,
    endFrame: 904},   
    
    { text: "በዚህ program", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 905, 
    endFrame: 945 },
    
   { text: "ከዜሮ ጀምራችሁ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 913,
    endFrame: 945},    
    
    { text: "እንዴት በ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 946, 
    endFrame: 970 },

    { text: "Video Editing", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 955, 
    endFrame: 970 },    
    
    { text: "clients ማግኘት",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 970,
    endFrame: 1030 },

    { text: "እንደምትችሉ ትማሩበታላችሁ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 980,
    endFrame: 1030 },
    
    { text: "የተማርናቸውን ነገሮች",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1130, 
    endFrame: 1165 },
    
     { text: "በሙሉ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1140, 
    endFrame: 1165 },   
    
    { text: "በዚህ program",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1167, 
    endFrame: 1200 },

    { text: "ላይ እንሰጣችኋለን",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1177, 
    endFrame: 1200 },
    
    { text: "በዚህ program ላይ theory",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 70,    
    startFrame: 1200, 
    endFrame: 1250 },
    
    { text: "ሳይሆን የምትማሩት",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1210, 
    endFrame: 1250 },
    
    { text: "የራሳችሁን client", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1390,
    endFrame: 1440 },
    
    { text: "ይዛችሁ መስራት የምትችሉ", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1400,
    endFrame: 1440 },
    
    { text: "editors",
    bottomOffset: 476,
    fontFamilyName: "SurGraphics",
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1440, 
    endFrame: 1475 },
    
    { text: "እንድትሆኑ እናደርጋችኋለን",
    bottomOffset: 400,
    fontFamilyName: "SurGraphics",
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1450, 
    endFrame: 1475 },    
    
    { text: "ስለዚህ program ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1525,
    endFrame: 1590 },

    { text: "ተጨማሪ መረጃዎችን የምትፈልጉ ከሆነ",
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    animation: "SmoothRevealText",
    fontSize: 55,    
    startFrame: 1535,
    endFrame: 1590 },
    
    { text: "ከዜሮ ጀምራችሁ ", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 476,
    animation: "SmoothRevealText",
    fontSize: 72,    
    startFrame: 1765, 
    endFrame: 1790 },

    { text: "በ Video Editing", 
    fontFamilyName: "SurGraphics",
    bottomOffset: 400,
    effect: "ChromeText", 
    animation: "SmoothRevealText",
    colors: ["#7dd0ff", "#7dd0ff", "#3d77fe"], 
    fontSize: 80,    
    startFrame: 1775, 
    endFrame: 1790 }
    
  ],
};
