export const videoData = {
  title: "Telebirr",
  audio: require("./telebrr.mp3"),
  mainVideo: null,
  mainVideoVolume: 1,
  brolls: [],
  subtitles: [
    { text: "Telebirr is Ethiopia's", startFrame: 0, endFrame: 45 },
    { text: "trusted digital payment solution,", startFrame: 45, endFrame: 105 },
    { text: "fast, simple,", startFrame: 105, endFrame: 135 },
    { text: "and secure.", startFrame: 135, endFrame: 165 },
    { text: "Send and receive money instantly,", startFrame: 165, endFrame: 225 },
    { text: "buy mobile airtime,", startFrame: 225, endFrame: 270 },
    { text: "and pay for electricity,", startFrame: 270, endFrame: 310 },
    { text: "water,", startFrame: 310, endFrame: 326},
    { text: "and many other services", startFrame: 326, endFrame: 365 },
    { text: "with just a few taps.", startFrame: 365, endFrame: 406 },
    { text: "Whether you're managing", startFrame: 406, endFrame: 435 },
    { text: "everyday expenses", startFrame: 435, endFrame: 473 },
    { text: "or making quick payments,", startFrame: 473, endFrame: 520 },
    { text: "Telebirr makes", startFrame: 520, endFrame: 535 },
    { text: "every transaction", startFrame: 535, endFrame: 575 },
    { text: "easy and reliable.", startFrame: 575, endFrame: 610 },
    { text: "Join the future", startFrame: 610, endFrame: 634 },
    { text: "of digital payments", startFrame: 634, endFrame: 660 },
    { text: "and experience a smarter,", startFrame: 660, endFrame: 702 },
    { text: "more convenient way", startFrame: 702, endFrame: 740 },
    { text: "to manage your money", startFrame: 740, endFrame: 770 },
    { text: "with Telebirr.", startFrame: 770, endFrame: 785 }
  ],
};
